### PR TITLE
Leaderboard implementation

### PR DESCRIPTION
**Pull request by psychonic**
I took a shot at implementing support for leaderboards.

The implementation uses three classes.

The GameLeaderboardManager class downloads the information about all of the leaderboards for the specified game and allows lookup of leaderboard by name or id. This gives a GameLeaderboard object.

The GameLeaderboard represents an individual leaderboard. Entry count, sorting info (whether leaderboard is ascending or decending), and display type (is score a number? a time?) are available for each GameLeaderboard.

Entries can then be fetched by either giving an entry range or specifying a steam user to get just their entry or entries of themselve and their friends. The GameLeaderEntry class contains the steamid64 of the user, their rank#, their score on the leaderboard, and the leaderboard that the entry belongs to.

As a side note, the output from this confirms that Issue #78 does affect the PHP version of Steam Condenser.

``` PHP

<?php

require_once STEAM_CONDENSER_PATH . "steam-condenser.php";
require_once STEAM_CONDENSER_PATH . "/steam/community/GameLeaderboardManager.php";

// Get TF2 leaderboard infos
$tf2boards = GameLeaderboardManager::createLeaderboardManager('tf2');

// Find the duel_wins board
if (($duelwins = $tf2boards->getLeaderboardByName('duel_wins')) === FALSE) {
    // board not found
}

$mysteam64 = SteamId::convertSteamIdToCommunityId('STEAM_0:1:4153990');
if (($myentry = $duelwins->getEntryForSteamId($mysteam64)) !== FALSE) {
    printf("%s rank of %d with score of %d\n",
        $myentry->getParentLeaderboard()->getName(),
        $myentry->getRank(),
        $myentry->getScore()
        );
}
else {
    print 'Not ranked on this board\n';
}

$entries = $duelwins->getEntryRange(1, 20);
foreach ($entries as $entry) {
    $steamid = new SteamId($entry->getSteamId64());
    printf("Rank: %d, Name: %s, Score %d\n",
        $entry->getRank(),
        $steamid->getNickname(),
        $entry->getScore()
        );
}

/*
Produces:
duel_wins rank of 6885 with score of 37
Rank: 1, Name: -=|JFH|=-JigglY, Score 17690
Rank: 2, Name: lovetheme, Score 14449
Rank: 3, Name: Yes. TF2 Is Still A Shitty Game, Score 13429
Rank: 4, Name: &gt;&gt;--THE CUNTSMAN---&gt;, Score 13370
Rank: 5, Name: Fireball, Score 8040
Rank: 6, Name: Berserker Terminator[ㅇㅅㅇ], Score 6840
Rank: 7, Name: KOSTYA {RU} in top 10 duelists, Score 5557
Rank: 8, Name: NeonHeights, Score 4225
Rank: 9, Name: Osman, Score 4161
Rank: 10, Name: {SuN} Scissors, Score 3779
Rank: 11, Name: скааа О_о, Score 3708
Rank: 12, Name: Mc.lovin, Score 3556
Rank: 13, Name: BiF.Drin, Score 3495
Rank: 14, Name: [ΖмBя.™] Purukinho, Score 3375
Rank: 15, Name: INKO-T, Score 3155
Rank: 16, Name: SWAT, Score 2871
Rank: 17, Name: Cannon Fodder52, Score 2847
Rank: 18, Name: extra° маки360(1шт), Score 2731
Rank: 19, Name: Platinum Rega [23/101], Score 2646
Rank: 20, Name: M0L0Tok, Score 2575

*/
?>

```

### CODE REVIEW

**Comment by psychonic** [comment]
I should also note that if the implementation looks alright (or after any necessary changes are made), I can probably port it to java as well if wanted. Ruby, however, I definitely don't feel as comfortable with (only done some minor hacking with it).

**Comment by koraktor** [comment]
I created a new branch with your work at [`leaderboards`](https://github.com/koraktor/steam-condenser/tree/leaderboards). Feel free to work with that branch and / or update your work. I'll try to keep on track and also provide the Ruby and Java implementations.

**Comment by koraktor** [comment]
I'm more or less done with my work. So this will be merged into master soon. Any further suggestions?

**Comment by psychonic** [comment]
I haven't touched it since last posting, but it should be fine as is if you're okay with the api (,and assuming that nothing has changed on Steam's end to break it).

**Comment by koraktor** [comment]
This is now in `master`.

**Pull request closed without merging**
