### PR TITLE
Removing closing tag

### PR DESCRIPTION
**Pull request by klaussilveira**
Minor change: for files containing only PHP code, the closing tag must always be omitted since it prevents the accidental injection of trailing white space into the response.

### CODE REVIEW

**Comment by koraktor** [comment]
Never thought about that, but it sounds reasonable.

PS: Looks ugly, though. But hey, it's PHP. ;)

**Comment by klaussilveira** [comment]
It's hard to get used to it, but once you do, it feels right. This is actually part of the Zend Framework coding style: http://framework.zend.com/manual/en/coding-standard.php-file-formatting.html#coding-standard.php-file-formatting.general

**Comment by koraktor** [comment]
Thanks!

**Comment by klaussilveira** [comment]
My pleasure. By the way, just bought you a beer using Pledgie. Great project. :)

**Pull request merged**
