### PR TITLE
Travis-CI integration

### PR DESCRIPTION
**Pull request by Holek**
This is not ready to be pulled yet, as it fails in ruby 1.9.2:
http://travis-ci.org/#!/Holek/steam-condenser/builds/251925

Have you checked it against 1.9.2 locally?

I mean, you can pull this, but we still have to fix the failing tests in 1.9.2

### CODE REVIEW

**Comment by koraktor** [comment]
I'm really glad to see some interest in unit testing and continuous integration.

But I must admit that the tests are mostly pretty useless, created before I started testing my other libraries. There's still some work to do to make CI really pay off.

Nevertheless this is really needed and I'm going to pull this once I checked the problem with 1.9.2.

**Comment by koraktor** [comment]
I merged your changes (I hope you don't mind I squashed them into on commit).

The code should just run fine on 1.9.2, it's just the tests that fail randomly (they use real servers :fire:).
As you might notice, the current [Travis run](http://travis-ci.org/#!/koraktor/steam-condenser/builds/253187) runs a few tests more than your initial `.travis.yml`. I added a Rake task that runs all tests and a few of them require a preconfigured server for RCON on localhost (that will never work on Travis).

I'm going to change the tests to be more useful and to work with mocks instead of real connections.

Thanks so far.

**Comment by Holek** [comment]
sure thing :)

btw, you might want to have a look at (vcr gem)[https://github.com/myronmarston/vcr] to record requests to the servers.

Not sure if it would work with this case, but I wouldn't mind having a look if it's possible to hack it a bit to do just that ;)

**Comment by koraktor** [comment]
Thanks for the hint, vcr looks interesting although it is HTTP only, so it would work only for the Steam Community.

**Pull request closed without merging**
