### PR TITLE
improved tests with mocks

### PR DESCRIPTION
**Pull request by gutomaia**
I've added a GutoMaiaSteamCommunityTest, I don't think that it is a good name, change suggestions are welcome. No documentation at all.

Now, the good part. The test uses mock to avoid the use of any external resource. It's also very fast, so it could be used for TDD.

I'm wililng to change tests that uses network resources for the integration test phase.

### CODE REVIEW

**Comment by koraktor** [comment]
Do we really need PowerMock? I made excellent experiences with standalone Mockito and I would rather stay with that, if there's not a really pressing argument for PowerMock.

**Comment by koraktor** [comment]
Additionally, you should definitely get rid of the Xerces dependency. [`DocumentBuilder#parse(java.io.File)`](http://docs.oracle.com/javase/7/docs/api/javax/xml/parsers/DocumentBuilder.html#parse%28java.io.File%29) should serve well for loading XML fixtures from file.

**Comment by gutomaia** [comment]
The objective of the tests is to mock the behavior of the DocumentBuilder and DocumentFactory, therefore the way acquired data is obtained isn't part of the scope of the test, and the data is fixed somehow.

The problem is that both of the them are used inside the SteamId object.
I need to mock or a static object, with in case is the newInstance or intercept every new construction of a object (whenNew). Unforgivably, Both of these features didn't come out of the box with Mockito.

We also needed it in the future for testing socket issues.

Of course that other alternatives of tests could be made, but that would inflict in change part of the code. Witch for now is not an option. The code isn't covered with tests.

I don't have the intention to change a line of the main source, just to increase the coverage of what we have now.

I need it to mock the static call

**Comment by gutomaia** [comment]
@koraktor, unfortunelly, I couldn't manage to use the DocumentBuilder.parse 'cause the DocumentBuilderFactory is static mocked. So in order to avoid confusing even on the verification process, I use xerces to generate the document that will be placed on the injected on the test.

That is pretty common in java, since I'm avoiding to use the same lib that I'm mocking. Unless, I've start stubbing just what I need, witch I don't think would do any good for now.

Think of code coverage. We can also improve the test latter on. But, for now, it is ok.

**Comment by koraktor** [comment]
What do you think about my [`xml-helper` branch](https://github.com/koraktor/steam-condenser/tree/xml-helper)?

I introduced a new class [`XMLData`](https://github.com/koraktor/steam-condenser/blob/xml-helper/java/src/main/java/com/github/koraktor/steamcondenser/steam/community/XMLData.java) which at the moment allows to inject a custom `DocumentBuilder` (e.g. for mocking). In the future I'd like to extend `XMLData` for the different XML-based objects to simplify XML access as noted in issue #76.

**Comment by gutomaia** [comment]
Well... It's a good aproach for using a single DocumentBuilder implementation. However it does come with side effects. The first is that you have to change the final code to use it without any code evolution pattern.

Using more than one implementation for me it's okay as long as i'm not 'causing side effects on the code. In my opinion the code must evolve without the tests dictating architecture opnion.

So, for now, I don't think that the XMLData stuff is nice. However, looking for a evolutionary goal for this implementation might be a good way to this lib to be supported on android.

I'm trying to build a simple android app that shows TF2Stats. For now, it's just an achievement list.

However i'm dealing with this error:

W/dalvikvm(  262): VFY: unable to resolve interface method 982: Lorg/w3c/dom/Node;.getTextContent ()Ljava/lang/String;
D/dalvikvm(  262): VFY: replacing opcode 0x78 at 0x0047
D/dalvikvm(  262): Making a copy of Lcom/github/koraktor/steamcondenser/steam/community/SteamId;.fetchData code (2141 bytes)
I/dalvikvm(  262): Could not find method org.w3c.dom.Node.getTextContent, referenced from method com.github.koraktor.steamcondenser.steam.community.SteamId.fetchData
W/dalvikvm(  262): VFY: unable to resolve interface method 982: Lorg/w3c/dom/Node;.getTextContent ()Ljava/lang/String;
D/dalvikvm(  262): VFY: replacing opcode 0x78 at 0x006e
W/System.err(  262): com.github.koraktor.steamcondenser.exceptions.SteamCondenserException: XML data could not be parsed.
W/System.err(  262):    at com.github.koraktor.steamcondenser.steam.community.SteamId.fetchData(SteamId.java:366)
W/System.err(  262):    at com.github.koraktor.steamcondenser.steam.community.SteamId.<init>(SteamId.java:261)
W/System.err(  262):    at com.github.koraktor.steamcondenser.steam.community.SteamId.create(SteamId.java:227)
W/System.err(  262):    at com.github.koraktor.steamcondenser.steam.community.SteamId.create(SteamId.java:201)
W/System.err(  262):    at net.guto.tf2stats.AchievementsList$LoadListTask.doInBackground(AchievementsList.java:64)
W/System.err(  262):    at net.guto.tf2stats.AchievementsList$LoadListTask.doInBackground(AchievementsList.java:50)
W/System.err(  262):    at android.os.AsyncTask$2.call(AsyncTask.java:185)
W/System.err(  262):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
W/System.err(  262):    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
W/System.err(  262):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1068)
W/System.err(  262):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:561)
W/System.err(  262):    at java.lang.Thread.run(Thread.java:1096)
W/System.err(  262): Caused by: org.xml.sax.SAXParseException: InputSource needs either stream or reader
W/System.err(  262):    at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:124)
W/System.err(  262):    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:201)
W/System.err(  262):    at com.github.koraktor.steamcondenser.steam.community.SteamId.fetchData(SteamId.java:294)
W/System.err(  262):    ... 11 more

I'm trying to build an app for Android 2.1_r1, sdk level 7

Even though android have the getTextContent method:
http://developer.android.com/reference/org/w3c/dom/Node.html

According to this forum:

http://groups.google.com/group/android-developers/browse_thread/thread/67181fee80e5b03b

It dosen't work. (yep, it really doesn't)

So I was thinking in change all calls to a static call that also could help on tests. 

profile.getElementsByTagName("onlineState").item(0).getTextContent();

to something like XmlData.get(profile, "onlineState");

that way... XmlData could deal, and also throws better exceptions, telling what was really wrong.

Also it could try to use the better getTextContent according to the enviroment. Like one that dosen't have the getTextContent, aka Android.

However, i'm againt the use of it to took out the xerces for tests. At least, not now.

**Comment by koraktor** [comment]
First of all, thank you very much for your efforts.

For now, I merged this into [`steam-condenser-java@xml-helper`](https://github.com/koraktor/steam-condenser-java/tree/xml-helper).

For the future, I would be happy if you could use feature branches and somewhat smaller and clearer commits. That would speed up merging a lot.

**Pull request closed without merging**
